### ISSUE TITLE
Requiring every payload file to be in every payload manifest

### ISSUE THREAD

**Issue by justinlittman** [LibraryOfCongress/bagit-spec#2]
Currently, every payload file must be in at least one payload manifest. The proposal is to change this to require every payload file to be in every payload manifest.

The motivation for this is that it reflects actual real world usage and reduces errors. However, it would mean that some existing bags may not be forward compatible with version 1.0.

Please add comments to this ticket.

**Comment by johnscancella** [comment]
Also please comment if you have bags that this change would cause problems so that we can gauge how widespread this issue is.

**Comment by justinlittman** [comment]
Based on discussion with @johnscancella and @jkunze, agree with this change with the caveat that it be identified that this is a change in BagIt 1.0.

**Comment by johnscancella** [comment]
@justinlittman @jkunze let me know if you want me to change the wording.
