### ISSUE TITLE
Tag and payload manifest checksum concordance

### ISSUE THREAD

**Issue by nkrabben** [LibraryOfCongress/bagit-spec#25]
I ran across a bag today that used sha256 for the payload manifest and md5 for the tag manifest. While there's nothing technically wrong with this according to the spec, it is awkward to work with. A recommendation to use the same algorithms between manifests would be useful to discourage that type of bag.

E.g Tag manifests should only use the hashing algorithm(s) as the payload manifests present in the bag.

**Comment by stain** [comment]
How about:

> Tag manifests SHOULD use the same algorithms as for the payload manifests in the bag.

**Comment by acdha** [comment]
This appears to be complete as of #28 merging
