### ISSUE TITLE
Reference RFC2234 for ABNF and core rules?

### ISSUE THREAD

**Issue by zimeon** [LibraryOfCongress/bagit-spec#4]
The current 1.0 branch doesn't mention [RFC2234](https://tools.ietf.org/html/rfc2234) as the source of ABNF syntax. 

It might also be good to explicitly mention core rules used, (e.g. DIGIT, HEXDIG) as is done in [RFC3986 - URI syntax](https://tools.ietf.org/html/rfc3986#section-1.3) for example

**Comment by johnscancella** [comment]
Thanks for the feedback! I accidentally tagged this under #3 but it has been updated to include the reference and a note about using the core rules.

**Comment by johnscancella** [comment]
see https://github.com/LibraryOfCongress/bagit-spec/commit/0b07d738030ec75fa39b28043e2605dca6741513

**Comment by zimeon** [comment]
Looks good, thanks
