### ISSUE TITLE
Should not have a MUST in a non-normative section

### ISSUE THREAD

**Issue by zimeon** [LibraryOfCongress/bagit-spec#7]
Currently, [6.1.1.3. Recommendations](https://github.com/LibraryOfCongress/bagit-spec/blob/0b07d738030ec75fa39b28043e2605dca6741513/bagit.xml#L1018) includes:

> Implementations MUST prevent the creation of bags containing files which differ only in normalization form.

if this stays in the non-normative section 6 then I think it can only be a SHOULD. (Another approach would be to avoid RFC2119 words in the non-normative portion.)

**Comment by justinlittman** [comment]
Based on discussion with @johnscancella and @jkunze, agree that should be changed to SHOULD.
